<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Contoh extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Contoh_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','contoh/contoh_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Contoh_model->json();
    }

    public function read($id) 
    {
        $row = $this->Contoh_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idconoth' => $row->idconoth,
		'isis' => $row->isis,
	    );
            $this->template->load('template','contoh/contoh_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('contoh'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('contoh/create_action'),
	    'idconoth' => set_value('idconoth'),
	    'isis' => set_value('isis'),
	);
        $this->template->load('template','contoh/contoh_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'isis' => $this->input->post('isis',TRUE),
	    );

            $this->Contoh_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('contoh'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Contoh_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('contoh/update_action'),
		'idconoth' => set_value('idconoth', $row->idconoth),
		'isis' => set_value('isis', $row->isis),
	    );
            $this->template->load('template','contoh/contoh_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('contoh'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idconoth', TRUE));
        } else {
            $data = array(
		'isis' => $this->input->post('isis',TRUE),
	    );

            $this->Contoh_model->update($this->input->post('idconoth', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('contoh'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Contoh_model->get_by_id($id);

        if ($row) {
            $this->Contoh_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('contoh'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('contoh'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('isis', 'isis', 'trim|required');

	$this->form_validation->set_rules('idconoth', 'idconoth', 'trim');
	$this->form_validation->set_error_delimiters('<div class="has-error"><label class="text-danger"><i class="fa fa-times-circle-o"></i> ', '</label></div>');
    }

}

/* End of file Contoh.php */
/* Location: ./application/controllers/Contoh.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-06 08:47:30 */
/* http://harviacode.com */