<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pelaporan_model extends CI_Model
{

    public $table = 'v_pelaporan';
    public $id = 'id_indikator';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id,$di) {
        $this->datatables->select('id_indikator,tahun,indikator,bulan,target,realisasi,capaian,id_satker,satker');
        $this->datatables->from('v_pelaporan');
        $this->datatables->add_column('indikator', '$1', 'add_symbolg(indikator,Indikator &#10148;,2)');
        $this->datatables->add_column('capaian', '$1', 'add_symbol(capaian)');
        $this->datatables->add_column('bulan', '$1', 'bulanindo(bulan)');
        $this->datatables->where('id_satker', $id);
        $this->datatables->where('tahun', $di);
        //add this line for join
        //$this->datatables->join('table2', 'v_pelaporan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pelaporan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('pelaporan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('pelaporan/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_indikator');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_indikator', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('indikator', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('target', $q);
	$this->db->or_like('realisasi', $q);
	$this->db->or_like('capaian', $q);
	$this->db->or_like('id_satker', $q);
	$this->db->or_like('satker', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_indikator', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('indikator', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('target', $q);
	$this->db->or_like('realisasi', $q);
	$this->db->or_like('capaian', $q);
	$this->db->or_like('id_satker', $q);
	$this->db->or_like('satker', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    // function insert($data)
    // {
    //     $this->db->insert($this->table, $data);
    // }

    // // update data
    // function update($id, $data)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->update($this->table, $data);
    // }

    // // delete data
    // function delete($id)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->delete($this->table);
    // }

}

/* End of file Pelaporan_model.php */
/* Location: ./application/models/Pelaporan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-15 08:50:46 */
/* http://harviacode.com */