<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Target_model extends CI_Model
{

    public $table = 'v_target';
    public $table2 = 'tbl_target';
    public $id = 'id_target';
    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
        
    }

    // datatables
    function json($id,$di) {
        
        $this->datatables->select('id_target,id_indikator,indikator,tahun,id_satker,id_users,bulan,target');
        $this->datatables->from('v_target');
        $this->datatables->add_column('bulan', '$1', 'bulanindo(bulan)');
        $this->datatables->where('id_satker', $id);
        $this->datatables->where('tahun', $di);
        //add this line for join
        //$this->datatables->join('table2', 'v_target.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('target/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))." 
            ".anchor(site_url('target/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm'))." 
                ".anchor('#','<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" data-href="'.site_url('target/delete/$1').'" data-toggle="modal" data-target="#confirm-delete"'), 'id_target');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_target', $q);
	$this->db->or_like('id_indikator', $q);
	$this->db->or_like('indikator', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('id_satker', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('target', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_target', $q);
	$this->db->or_like('id_indikator', $q);
	$this->db->or_like('indikator', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('id_satker', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('target', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    { var_dump($data);
        $this->db->insert($this->table2, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table2, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table2);
    }

}

/* End of file Target_model.php */
/* Location: ./application/models/Target_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-06 14:33:42 */
/* http://harviacode.com */